name: Deploy to Local Kind Cluster

on:
  push:
    branches:
      - main

jobs:
  deploy-local:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create deployment script
      run: |
        cat << 'EOF' > deploy-local.sh
        #!/bin/bash
        set -e

        # Verify kind cluster
        if ! kind get clusters | grep -q "kind"; then
          echo "Kind cluster not found. Please create one first."
          exit 1
        fi

        # Add Helm repos
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo update

        # Create namespace
        kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -

        # Install Prometheus Stack
        helm upgrade --install prometheus prometheus-community/kube-prometheus-stack \
          --namespace monitoring \
          --set grafana.adminPassword=admin \
          --wait

        # Install Blackbox Exporter
        helm upgrade --install prometheus-blackbox-exporter prometheus-community/prometheus-blackbox-exporter \
          --namespace monitoring \
          --values black-values.yaml \
          --wait

        # Port forward services
        echo "Starting port forwards..."
        kubectl port-forward -n monitoring svc/prometheus-grafana 3000:80 &
        kubectl port-forward -n monitoring svc/prometheus-operated 9090:9090 &
        kubectl port-forward -n monitoring svc/prometheus-blackbox-exporter 9115:9115 &

        echo "Access URLs:"
        echo "Grafana: http://localhost:3000 (admin/admin)"
        echo "Prometheus: http://localhost:9090"
        echo "Blackbox Exporter: http://localhost:9115"
        EOF

        chmod +x deploy-local.sh

    - name: Make script executable
      run: chmod +x deploy-local.sh

    - name: Deploy to local kind cluster
      run: ./deploy-local.sh
